name: OpenCBee

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install tesseract
      run: sudo apt update sudo apt install tesseract-ocr
    - name: Install pipenv
      run: pip install pipenv
    - name: Run tests
      run: |
        pipenv install --dev
        pipenv run python setup.py develop
        pipenv run pytest
        pipenv run pylint app/